version: '3.4'
services:
  client:
    image: mhart/alpine-node:12
    container_name: react-remote-modules-poc-client
    working_dir: /app
    entrypoint: /bin/sh entrypoint.sh
    command: npm start
    volumes:
      - ./client:/app
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3333

  server:
    image: mhart/alpine-node:12
    container_name: react-remote-modules-poc-server
    working_dir: /app
    entrypoint: /bin/sh entrypoint.sh
    command: npm start
    volumes:
      - ./server:/app
    ports:
      - "3333:3333"
